"use client";

import { useEffect, useMemo, useState } from "react";

type Lesson = { eyebrow: string; title: string; summary: string; body: React.ReactNode };
type Question = { q: string; options: string[]; answer: number; explanation: string };
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

const lessons: Lesson[] = [
  { eyebrow: "01 · Foundations", title: "Your role in fire safety", summary: "Understand the UK legal framework and the everyday actions expected of staff.", body: <><p>The Regulatory Reform (Fire Safety) Order 2005 is the main law for most non-domestic premises in England and Wales. The responsible person must assess risk, provide suitable precautions, plan for emergencies, inform and train staff, and keep arrangements under review.</p><div className="callout"><strong>Your part</strong><span>Follow training, report hazards and defects, never interfere with fire precautions, and know the alarm, exits and assembly arrangements at your workplace.</span></div><p className="fine">Scotland and Northern Ireland have separate fire-safety regimes. Always follow the legislation and procedures that apply to your premises.</p></> },
  { eyebrow: "02 · Fire behaviour", title: "The fire triangle", summary: "Recognise the three ingredients a fire needs—and how controls keep them apart.", body: <><div className="triangle"><div className="triangleTop"><b>HEAT</b><span>electrical faults · heaters · hot work</span></div><div><b>FUEL</b><span>paper · packaging · solvents · waste</span></div><div><b>OXYGEN</b><span>normally present in air</span></div></div><p>A fire needs heat, fuel and oxygen. Remove any one and combustion cannot continue. Smoke can spread quickly, obscure exits and contain toxic gases, so never assume a small fire will stay small.</p></> },
  { eyebrow: "03 · Prevention", title: "Common causes and controls", summary: "Spot common ignition risks before they become emergencies.", body: <><div className="gridList"><div><b>Electrical</b><span>Damaged leads, overloaded sockets, hot plugs and unsuitable charging.</span></div><div><b>Cooking & heating</b><span>Unattended cooking and combustibles too close to heat.</span></div><div><b>Hot work</b><span>Grinding, welding or cutting without controls and a fire watch.</span></div><div><b>Flammables</b><span>Poor storage, open containers, vapours or incompatible materials.</span></div><div><b>Smoking & arson</b><span>Unsafe disposal and insecure external waste.</span></div><div><b>Lithium-ion batteries</b><span>Damage, swelling, overheating or incompatible chargers.</span></div></div></> },
  { eyebrow: "04 · Housekeeping", title: "Small actions, safer workplaces", summary: "Use a simple daily routine to reduce fire risk and protect escape routes.", body: <><ul className="checks"><li>Keep corridors, stairs, final exits and fire equipment clear.</li><li>Remove waste and store combustibles safely.</li><li>Report scorching, unusual heat, smells, sparks or repeated tripping.</li><li>Use approved chargers and charging locations.</li><li>Keep heaters clear and follow hot-work permits.</li><li>Never wedge a fire door open.</li></ul><div className="callout amber"><strong>Report it</strong><span>If a control is missing or defective, use your local reporting route promptly. Do not assume somebody else has reported it.</span></div></> },
  { eyebrow: "05 · Escape", title: "Means of escape and fire doors", summary: "Choose a safe route and understand why closed fire doors buy time.", body: <><p>Use the nearest safe signed route—not necessarily the entrance you used. Walk calmly, leave belongings, and never use an ordinary lift. If smoke or fire affects your route, turn away and use an alternative.</p><div className="doDont"><div><h3>Do</h3><p>Let fire doors close fully. Report damage, failed latches, missing seals or broken glazing.</p></div><div><h3>Don’t</h3><p>Wedge, tie or prop doors open. Never enter smoke or go towards visible fire.</p></div></div><p className="fine">Only use a lift where the emergency plan specifically identifies a suitable evacuation lift and trained procedure.</p></> },
  { eyebrow: "06 · Alarm", title: "Raise the alarm without delay", summary: "Know exactly what to do when you discover fire or signs of fire.", body: <><ol className="steps"><li><b>Raise the alarm</b><span>Use the nearest call point or the site’s stated method.</span></li><li><b>Leave</b><span>Take the nearest safe route. Warn others only if it does not delay your escape.</span></li><li><b>Call for help</b><span>From safety, call 999 or 112 if required by the local plan. Give the full address and location of the fire.</span></li><li><b>Report</b><span>Go to the assembly point and pass on useful information.</span></li></ol></> },
  { eyebrow: "07 · Evacuation", title: "When the alarm sounds", summary: "Evacuate, account for people and wait for formal instruction.", body: <><ul className="checks"><li>Stop work and leave immediately.</li><li>Close doors behind you if safe; do not lock them.</li><li>Assist others only in line with the emergency plan.</li><li>Go to the assembly point and follow roll-call arrangements.</li><li>Report anyone believed missing and their last known location.</li><li>Never go back to search or collect belongings.</li><li>Do not re-enter until formally authorised.</li></ul><div className="callout"><strong>Every alarm is real</strong><span>Treat it as genuine unless an authorised instruction says otherwise. A silenced alarm is not permission to re-enter.</span></div></> },
  { eyebrow: "08 · Equipment", title: "Portable extinguishers", summary: "Know their purpose, their limitations and when evacuation is the only safe choice.", body: <><div className="danger"><strong>Life safety comes first.</strong><p>Only consider an extinguisher if policy permits, you are trained, the alarm is raised, the fire is very small and contained, the correct appliance is available, and a clear exit remains behind you.</p></div><div className="pass"><span><b>P</b>Pull the pin</span><span><b>A</b>Aim at the base</span><span><b>S</b>Squeeze the handles</span><span><b>S</b>Sweep side to side</span></div><p>Stop immediately if the fire spreads, smoke increases, you feel heat, one extinguisher does not control it quickly, or you have any doubt. Get out, stay out and call 999/112.</p></> },
  { eyebrow: "09 · People", title: "Roles and responsibilities", summary: "Understand how staff, managers and wardens work together.", body: <><div className="roleRows"><p><b>All staff</b><span>Prevent, report, raise the alarm and evacuate.</span></p><p><b>Managers</b><span>Make local controls, induction and corrective actions effective.</span></p><p><b>Wardens</b><span>Carry out defined checks, guide evacuation and report area status—without unsafe risk.</span></p><p><b>Visitors & contractors</b><span>Receive essential information, sign in/out and follow host arrangements.</span></p></div><p className="fine">Local titles and duties vary. Nobody should delay their own escape, enter smoke or fight a fire unless that exact activity is risk-assessed, trained, equipped and authorised.</p></> },
  { eyebrow: "10 · Inclusion", title: "Vulnerable persons", summary: "Plan for people who may need information, time, equipment or assistance.", body: <><p>Needs may relate to mobility, sensory or cognitive differences, health, language, age, pregnancy, injury or temporary circumstances. Use a respectful, person-centred discussion—never assumptions.</p><ul className="checks"><li>Prepare and review a PEEP for staff or regular visitors who need one.</li><li>Provide suitable standard arrangements for occasional visitors.</li><li>Confirm alarm communication, assistance and backup arrangements.</li><li>Only trained people should use specialist evacuation equipment.</li><li>A refuge is a temporary managed waiting area, not a place to leave someone without communication.</li></ul></> },
];

const questions: Question[] = [
  { q: "What three elements make up the fire triangle?", options: ["Heat, fuel and oxygen", "Smoke, flame and water", "Fuel, carbon and steam", "Heat, alarms and exits"], answer: 0, explanation: "A fire needs heat, fuel and oxygen." },
  { q: "You discover smoke from a waste bin. What should you do first?", options: ["Find an extinguisher", "Raise the alarm", "Open a window", "Finish your task"], answer: 1, explanation: "Raise the alarm immediately, then evacuate by a safe route." },
  { q: "Why must fire doors not be wedged open?", options: ["They become harder to clean", "They protect against fire and smoke when closed", "They use too much power", "They stop the alarm sounding"], answer: 1, explanation: "Closed fire doors protect compartmentation and escape routes." },
  { q: "Which exit should you normally use when the alarm sounds?", options: ["The entrance you arrived through", "The nearest safe signed exit", "The staff entrance", "The nearest lift"], answer: 1, explanation: "Use the nearest safe signed route and follow local instructions." },
  { q: "When may a lift be used during evacuation?", options: ["Whenever stairs are busy", "If it is an ordinary passenger lift", "Only when the plan identifies a suitable evacuation lift and procedure", "Whenever a manager is present"], answer: 2, explanation: "Ordinary lifts must not be used; only a planned evacuation-lift arrangement is suitable." },
  { q: "Which condition must be met before considering an extinguisher?", options: ["The fire is blocking your exit", "You have a clear exit behind you", "The room is filling with smoke", "The fire is spreading"], answer: 1, explanation: "A clear escape route behind you is essential, alongside training, permission and a very small contained fire." },
  { q: "What does PASS stand for?", options: ["Point, Alert, Stop, Shout", "Pull, Aim, Squeeze, Sweep", "Push, Assess, Stand, Spray", "Pause, Alarm, Signal, Sweep"], answer: 1, explanation: "PASS means Pull, Aim, Squeeze, Sweep." },
  { q: "One extinguisher does not control the fire quickly. What next?", options: ["Find a second one", "Move closer", "Evacuate, stay out and report", "Turn your back on it"], answer: 2, explanation: "Stop immediately, evacuate, stay out and pass information to responders." },
  { q: "What is a PEEP?", options: ["A fire-door inspection label", "A Personal Emergency Evacuation Plan", "A portable extinguisher test", "A public exit and entry point"], answer: 1, explanation: "A PEEP is tailored to a person’s needs and the premises arrangements." },
  { q: "Who should report a fire-safety defect?", options: ["Only the fire warden", "Only senior managers", "Anyone who notices it", "Only the maintenance team"], answer: 2, explanation: "Everyone should report defects promptly through the local route." },
];

export default function Home() {
  const [started, setStarted] = useState(false);
  const [index, setIndex] = useState(0);
  const [completed, setCompleted] = useState<number[]>([]);
  const [quiz, setQuiz] = useState(false);
  const [answers, setAnswers] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const [name, setName] = useState("");
  const [company, setCompany] = useState("");
  const [hydrated, setHydrated] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem("fire-course-progress-v1");
    if (saved) { try { const p = JSON.parse(saved); setCompleted(p.completed || []); setIndex(p.index || 0); setStarted(Boolean(p.started)); } catch {} }
    setHydrated(true);
  }, []);
  useEffect(() => { if (hydrated) localStorage.setItem("fire-course-progress-v1", JSON.stringify({ completed, index, started })); }, [completed, index, started, hydrated]);

  const score = useMemo(() => questions.reduce((n, q, i) => n + (answers[i] === q.answer ? 1 : 0), 0), [answers]);
  const percent = score * 10;
  const passed = submitted && percent >= 80;
  const finishLesson = () => {
    setCompleted(c => c.includes(index) ? c : [...c, index]);
    if (index < lessons.length - 1) { setIndex(index + 1); window.scrollTo({ top: 0, behavior: "smooth" }); }
    else { setQuiz(true); window.scrollTo({ top: 0, behavior: "smooth" }); }
  };
  const resetQuiz = () => { setAnswers({}); setSubmitted(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const resetCourse = () => { localStorage.removeItem("fire-course-progress-v1"); setStarted(false); setCompleted([]); setIndex(0); setQuiz(false); setAnswers({}); setSubmitted(false); };

  if (!hydrated) return <main className="loading">Preparing your course…</main>;

  return <main>
    <header className="topbar"><a className="brand" onClick={() => { setQuiz(false); setStarted(false); }} aria-label="Protec Fire Safety Ltd — course home"><img src={`${basePath}/assets/protec-logo.png`} alt="Protec Fire Safety Ltd" /></a>{started && <div className="progressWrap"><span>{quiz ? "Final assessment" : `Module ${index + 1} of ${lessons.length}`}</span><div className="progress"><i style={{width: `${quiz ? 100 : Math.max(((index) / lessons.length) * 100, 3)}%`}} /></div></div>}</header>

    {!started && <section className="hero"><div className="heroCopy"><span className="pill">UK workplace fire awareness</span><h1>Know what to do.<br/><em>Before it matters.</em></h1><p>A clear, practical course for workplace staff. Learn how to prevent fire, raise the alarm, evacuate safely and understand the limits of portable extinguishers.</p><div className="heroActions"><button onClick={() => setStarted(true)}>Start course <span>→</span></button>{completed.length > 0 && <button className="textButton" onClick={() => setStarted(true)}>Continue from module {index + 1}</button>}</div><div className="meta"><span><b>10</b> learning modules</span><span><b>~45</b> minutes</span><span><b>80%</b> pass mark</span><span><b>✓</b> printable certificate</span></div></div><div className="heroCard"><span className="cardKicker">Your outcome</span><h2>Confident action saves time.</h2><ol><li><b>Prevent</b> common workplace fires</li><li><b>Respond</b> quickly to warning signs</li><li><b>Escape</b> using safe procedures</li><li><b>Protect</b> people who need support</li></ol><div className="legal">Based on the Regulatory Reform (Fire Safety) Order 2005 and current workplace guidance.</div></div></section>}

    {started && !quiz && <div className="courseShell"><aside><span className="asideLabel">Course contents</span><nav>{lessons.map((l,i) => <button key={l.title} className={`${i===index?"active":""} ${completed.includes(i)?"done":""}`} onClick={() => setIndex(i)}><i>{completed.includes(i)?"✓":String(i+1).padStart(2,"0")}</i><span>{l.title}</span></button>)}</nav><button className="reset" onClick={resetCourse}>Restart course</button></aside><article className="lesson"><div className="lessonHead"><span>{lessons[index].eyebrow}</span><h1>{lessons[index].title}</h1><p>{lessons[index].summary}</p></div><div className="lessonBody">{lessons[index].body}</div><div className="lessonFoot"><button className="back" disabled={index===0} onClick={() => setIndex(index-1)}>← Previous</button><button className="primary" onClick={finishLesson}>{index===lessons.length-1 ? "Take the assessment" : "Complete & continue"} →</button></div></article></div>}

    {started && quiz && !submitted && <section className="quiz"><div className="quizIntro"><span>Final assessment</span><h1>Show what you know</h1><p>Answer all ten questions. You need at least 8 correct answers to pass and unlock your certificate.</p><div className="scoreRule"><b>80%</b><span>pass mark<br/>8 out of 10</span></div></div><div className="questions">{questions.map((q,i)=><fieldset key={q.q}><legend><span>{String(i+1).padStart(2,"0")}</span>{q.q}</legend>{q.options.map((o,j)=><label key={o} className={answers[i]===j?"chosen":""}><input type="radio" name={`q${i}`} checked={answers[i]===j} onChange={()=>setAnswers({...answers,[i]:j})}/><i></i>{o}</label>)}</fieldset>)}<button className="submit" disabled={Object.keys(answers).length!==10} onClick={()=>{setSubmitted(true);window.scrollTo({top:0,behavior:"smooth"})}}>Submit assessment</button><p className="answered">{Object.keys(answers).length} of 10 answered</p></div></section>}

    {started && quiz && submitted && <section className="result"><div className={`resultHero ${passed?"pass":"fail"}`}><span>{passed?"Course complete":"Not quite this time"}</span><div className="scoreRing"><b>{percent}%</b><small>{score}/10 correct</small></div><h1>{passed?"You passed.":"Review and try again."}</h1><p>{passed?"Well done. Enter your details to create your completion certificate.":"You need 80% to pass. Review the answers below, revisit any modules you need, then retake the assessment."}</p></div><div className="review">{questions.map((q,i)=><div key={q.q} className={answers[i]===q.answer?"correct":"incorrect"}><span>{answers[i]===q.answer?"✓":"×"}</span><div><b>{q.q}</b><p>{q.explanation}</p></div></div>)}</div>{passed?<div className="certificateForm"><div><span>Certificate details</span><h2>Make it official</h2><p>Your details appear exactly as entered. Use Print / Save PDF to keep a digital copy.</p></div><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Alex Morgan"/></label><label>Company or organisation<input value={company} onChange={e=>setCompany(e.target.value)} placeholder="e.g. Northstar Ltd"/></label><button disabled={!name.trim() || !company.trim()} onClick={()=>window.print()}>Print certificate</button></div>:<div className="retry"><button onClick={resetQuiz}>Retake assessment</button><button className="back" onClick={()=>{setSubmitted(false);setQuiz(false);setIndex(0)}}>Review course</button></div>}
      {passed && <section className="certificate"><div className="certBorder"><div className="certMark">F</div><p className="certKicker">Certificate of completion</p><h1>Workplace Fire Awareness</h1><p className="awarded">This certifies that</p><h2>{name || "Participant name"}</h2><p>of <b>{company || "Organisation"}</b> has successfully completed workplace fire awareness training and achieved the required pass mark.</p><div className="certStats"><span><b>{percent}%</b>Assessment score</span><span><b>{new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</b>Date completed</span><span><b>80%</b>Required pass mark</span></div><p className="certNote">Training should be supplemented by the organisation’s premises-specific fire procedures and risk assessment.</p></div></section>}
    </section>}
    <footer><span>FireAware workplace training</span><span>General awareness only · Follow your premises-specific fire procedures</span></footer>
  </main>;
}
